SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HotelPhoneNumber](
	[ContactName] [nvarchar](450) NOT NULL,
	[PhoneNumber] [nvarchar](max) NOT NULL,
	[Hotel_Hotel_ID] [nvarchar](450) NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
ALTER TABLE [dbo].[HotelPhoneNumber] ADD  CONSTRAINT [PK_HotelPhoneNumber] PRIMARY KEY CLUSTERED 
(
	[ContactName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [IX_HotelPhoneNumber_Hotel_Hotel_ID] ON [dbo].[HotelPhoneNumber]
(
	[Hotel_Hotel_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[HotelPhoneNumber]  WITH CHECK ADD  CONSTRAINT [FK_HotelPhoneNumber_Hotel_Hotel_Hotel_ID] FOREIGN KEY([Hotel_Hotel_ID])
REFERENCES [dbo].[Hotel] ([Hotel_ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[HotelPhoneNumber] CHECK CONSTRAINT [FK_HotelPhoneNumber_Hotel_Hotel_Hotel_ID]
GO
