SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RoomIssue](
	[RoomNumber] [nvarchar](450) NOT NULL,
	[Problem] [nvarchar](450) NOT NULL,
	[Description] [nvarchar](max) NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
ALTER TABLE [dbo].[RoomIssue] ADD  CONSTRAINT [PK_RoomIssue] PRIMARY KEY CLUSTERED 
(
	[RoomNumber] ASC,
	[Problem] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RoomIssue]  WITH CHECK ADD  CONSTRAINT [FK_RoomIssue_Room_RoomNumber] FOREIGN KEY([RoomNumber])
REFERENCES [dbo].[Room] ([RoomID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[RoomIssue] CHECK CONSTRAINT [FK_RoomIssue_Room_RoomNumber]
GO
